<a href="https://colab.research.google.com/github/sreeson/data-science-lab/blob/main/1_b_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [3]:
print(type(x))


<class 'numpy.ndarray'>


In [4]:
print(x.shape)

(4,)


In [5]:
y=np.array([[1,2],[3,4]])
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [7]:
z=np.array([[1+0.j, 2.+5.j]])
print(z)
print(z.shape)


[[1.+0.j 2.+5.j]]
(1, 2)


In [8]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(a.shape)

(2, 3)


In [11]:
b=np.ones((2,3), dtype=int)
print(b)

[[1 1 1]
 [1 1 1]]


In [12]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
e=np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
e=np.arange(12,21)
print(e)

[12 13 14 15 16 17 18 19 20]


In [17]:
e=np.arange(5,20,3)
print(e)

[ 5  8 11 14 17]


In [18]:
f=np.linspace(1,20,7)
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [19]:
g=np.random.random((3,4))
print(g)

[[0.81944533 0.14884615 0.25598529 0.06255259]
 [0.47894836 0.12074462 0.21977321 0.68160267]
 [0.22963222 0.40702545 0.39056    0.61379135]]


In [21]:
h=np.random.random((3,4))
print(h.reshape(2,2,3))

[[[0.02232973 0.32554439 0.33319821]
  [0.96153791 0.42350185 0.25680993]]

 [[0.94797604 0.11464475 0.04546174]
  [0.4096359  0.28535836 0.02493223]]]


In [23]:
x=np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [24]:
print(x[-1])

11


In [25]:
x.resize(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
print(x[2][3])

11


In [27]:
y=np.arange(1,26)
print(y)
print(y[:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3]


In [28]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [29]:
print(y[10:24])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [30]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [31]:
print(y[-5:])

[21 22 23 24 25]


In [33]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [34]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [36]:
y=y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [38]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [39]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [41]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [42]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [43]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [45]:
a=np.arange(1,6)
b=np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [46]:
print(a>3)

[False False False  True  True]


In [47]:
a=np.arange(0,4).reshape((2,2))

In [48]:
b=np.eye(2)
print(b)

[[1. 0.]
 [0. 1.]]


In [49]:
print(a*b)

[[0. 0.]
 [0. 3.]]


In [50]:
print(np.dot(a,b))

[[0. 1.]
 [2. 3.]]


In [52]:
x=np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(x.sum())

45


In [54]:
print(x.sum(axis=0))

[12 15 18]


In [56]:
print(x.sum(axis=1))

[ 6 15 24]


In [57]:

x=np.arange(1,10).reshape(3,3)

In [58]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [59]:
print(x.max(axis=0))

[7 8 9]


In [60]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
